### ISSUE TITLE
NPC not recognizing animation

### ISSUE THREAD

**Issue by makendym** [taulantxhakli/Discrimination#2]
When I add new animation to the npc and even downloaded new animations so I can animate the Npc's. The Npc's will not animate and I am not sure why. Only a selected few animations that work, like the sitting animation and a stand still animation. I have tried several methods and I can't seem to figure it out.

**Comment by makendym** [comment]
Look at the store Npc's and you will see what I am talking about.

**Comment by taulantxhakli** [comment]
A couple of things I have found in relation to the animations.
It seems that the NPCs are missing some critical scripts and references for their animation. I would recommend to see the walking NPCs and compare the two.

But including that, a bunch of other things have been deleted and/or ruined from last time I used it. 
For starters, some NPCs that had no problem before with animations now do not animate, this could be an asset that got deleted.
![Unity_7CthwgXQkC](https://user-images.githubusercontent.com/58316986/142778871-0e5a6fbb-d755-4b0a-a85c-9e6a16724f46.png)
![Unity_u32HQakoTK](https://user-images.githubusercontent.com/58316986/142778876-5ee4b7ff-96f0-4cf6-8571-6b27a0584f89.png)


Also, the reveal scenes that I finished and did everything in, I guess one of you or Michael had deleted all the work that I did in the rooms. That would need to be re-done and that can take a lot of time from the beginning. With that said, I am not sure what was the intention of adding this to the controller:
![Unity_9AKAwrhC2K](https://user-images.githubusercontent.com/58316986/142778905-ca098e65-c460-4081-a14a-44be7838bc8a.png)
If you remember, we agreed to have the hands faded so the person does not know who they are playing as until the reveal. You guys will need to look into who added that and remove it completely. 

Other small issues I have seen are textures and mesh not working properly. Such as the out-of-bounds garage area:
![Unity_Va7u8DLB1Z](https://user-images.githubusercontent.com/58316986/142778933-9191fd2a-9c20-458e-afce-398b4cee8192.png)


I would suggest to look into why these things have happened and what you can do to fix it while I am gone.
Meanwhile, when I return, I will see if I can get my old project commit again, though that will not be possible, I think. But, it is worth a try. Last time I touched the project everything was working properly and I saw no issues, so it had to definitely have been from the wrongful committing and whatever Michael, or someone else, have done.

**Comment by taulantxhakli** [comment]
I got the commit I made from June on my computer and tested it. Works like a charm and has a significantly lower file size too. Plus all of the things I did with it.
I will be wiping the repo and putting the new(or old) project into this repo when I can.
